### ISSUE TITLE
Suspected error in ingest_training cli

### ISSUE THREAD

**Issue by loicdtx** [CONABIO/antares3#21]
I suspect the `interpret_tag = Tag.objects.get(numeric_code=value, scheme=scheme)`, line 85 in the `ingest_training` cli should be replaced by `interpret_tag = Tag(numeric_code=value, scheme=scheme)`.
Alternatively the whole try/catch block could be replaced by a `Tag.objects.get_or_create()`

**Comment by amaurs** [comment]
The bug was fixed. I am using `Tag.objects.get_or_create()`, also fixed documentation.
