### ISSUE TITLE
column model_id of table madmex_predictclassification could change?

### ISSUE THREAD

**Issue by palmoreck** [CONABIO/antares3#46]
When doing classification workflow for sentinel2 the task  was to fit a model using bands of 20m resolution and classify segments generated from sentinel2 10m bands. Although this was accomplished it was noted that using:

```
antares model_predict_object -p sentinel_10m_ndvi_mean_jalisco_001_recipe_2017 -m lgb_sentinel_jalisco_2017 -s sentinel_10m_jalisco_seg_2017 -r Jalisco --name land_cover_jalisco_20m_10m_sentinel_2017 -sc /shared_volume/scheduler.json
```

didn't function because table madmex_predictclassification has a column called model_id and because no model was trained with sentinel_10m_ndvi_mean_jalisco_001_recipe_2017 then registering in DB could be failing....Do we need to have that column on madmex_predictclassification table?

This next line did work:

```
antares model_predict_object -p sentinel_jalisco_001_recipe_2017 -m lgb_sentinel_jalisco_2017 -s sentinel_10m_jalisco_seg_2017 -r Jalisco --name land_cover_jalisco_20m_10m_sentinel_2017 -sc /shared_volume/scheduler.json
```

```sentinel_jalisco_001_recipe_2017``` used 20m resolution bands and ```sentinel_10m_jalisco_seg_2017``` was generated using ndvi with 10m bands resampling from 20m bands (s2 20m scenes were ingested to DB)

**Comment by loicdtx** [comment]
The second comand is the proper way to do it. What were you trying to achieve with the first comand (the one that failed)?
