### ISSUE TITLE
About merging collections

### ISSUE THREAD

**Issue by loicdtx** [CONABIO/antares3#51]
Some recipes merge multiples collections (e.g. combine Landsat data from different sensors). The way things are implemented now probably won't work.

- `xr.auto_combine([...], concat_dim='time')` does a better job than `xr.merge` or `xr.concat` for combining the `Datasets`. `xr.merge` coerces all arrays to float (problem for bitmask), and `xr.concat` fails when one of the `Dataset` is empty.
- If attributes of a `DataArray` are different between the collections, it is lost (e.g. `pixel_qa` flag definition between ls8 and other landsat sensors). Important to use the least common denominator when defining the flags of a collection (e.g. Delete [this](https://github.com/CONABIO/antares3/blob/6ba8619b787f23559a99bea34919e72aecea13be/madmex/conf/indexing/ls8_espa_scenes.yaml#L83-L94) and [this](https://github.com/CONABIO/antares3/blob/6ba8619b787f23559a99bea34919e72aecea13be/madmex/conf/ingestion/ls8_espa_mexico.yaml#L149-L160))

**Comment by palmoreck** [comment]
ok, I removed cirrus_confidence and terrain_oclusion of L8:

https://github.com/CONABIO/antares3/commit/3c0515ee4fe443aec2fd44b07a88adba2c6fd054

https://github.com/CONABIO/antares3/commit/293fe20b7c2cb73be74ac47dc58d0b3297efae8e

**Comment by palmoreck** [comment]
not sure if i need to change some flags when using ```xr.auto_combine``` instead of ```xr.merge``` I'll look it up

**Comment by palmoreck** [comment]
issue solved by:
1a9c1835af2d0508d60edc5e628df2da7ef1de04

**Comment by palmoreck** [comment]
closing issue
