### ISSUE TITLE
Use rasterio.warp.transform_geom

### ISSUE THREAD

**Issue by loicdtx** [CONABIO/antares3#58]
instead of cutom made `madmex.util.spatial.geometry_transform`

https://rasterio.readthedocs.io/en/stable/api/rasterio.warp.html#rasterio.warp.transform_geom

**Comment by palmoreck** [comment]
Listo, revisaré otros lugares en los que reemplazar la sugerencia de
rio.warp

https://github.com/CONABIO/antares3/commit/04285adc1c207e8b830cf29c0ba7dbb8ac2232ad

**Comment by loicdtx** [comment]
Más simple es usar transform_geom adentro de geometry_transform y no cambiar nada más
